name: version_tracking
description: Xamarin.Essentials VersionTracking for Flutter. 
version: 1.0.2
homepage: https://www.github.com/jamiewest/version_tracking
author: Jamie West <jamiewst@gmail.com>

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+4
  package_info: '>=0.4.0+5 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any